### ISSUE TITLE
Fix kotlog binary generation

### ISSUE THREAD

**Issue by tscholze** [tscholze/kotlin-kotlog-cli#34]
**Problem**
The standalone kotlog binary is not executable if it is copied from the `build` folder.

**Possible solution**
See Discord message from: @bitspittle

https://discord.com/channels/886036660767305799/886036660767305802/1045033217759133787

**Comment by bitspittle** [comment]
Note that, even with a fat jar, the user will still need to have Java installed on their system.

If you wanted a truly independent program, one that could run without Java, then there is a solution there too: you build a binary that has Java embedded inside of it.

There are disadvantages with that approach though:
* You have to create one executable per system (e.g. Windows, Linux, and Mac need to be compiled separately)
* It makes your final executable size significantly larger
* If you ever happened to bundle a version of Java with some security issue discovered down the line, it doesn't matter if users update Java on their system to the latest version because your program will still run with the older version.

So don't make it a requirement if you don't have to! But if this is what you wanted, you can take a look at graalvm as one approach.

**Comment by tscholze** [comment]
@bitspittle thanks for pointing it out!

I guess what I want is to be able to have `kotlog -c 'Hi BitSpittle'` instead of `java -jar kotlog ...` and require that Java is installed.

I mean, this is still a "I wrote it for my self tool" but to get rid if the `java -jar` stuff would be awesome.

**Comment by tscholze** [comment]
@bitspittle I know that I try this a few weeks now but I think I'm going around in circles.

**Comment by bitspittle** [comment]
My recommendation for now is to make Java being installed locally a requirement (you can always change that later). Use the Gradle application plugin (which you're already doing),  then distribute a compressed file (using `gradlew distZip` or `distJar`) and require people add `path/to/unzipped/kotlog/bin` to their PATH.

In my opinion this is good enough for a first pass, especially if you still only have very very few users, and can be improved later without too much effort.
